import {
  pgTable,
  text,
  integer,
  timestamp,
  doublePrecision,
} from "drizzle-orm/pg-core";

const buddhashantiHousehold = pgTable("buddhashanti_household", {
  id: text("id").primaryKey().notNull(),
  tenantId: text("tenant_id").default("khajura"),
  province: text("province"),
  district: text("district"),
  localLevel: text("local_level"),
  wardNo: integer("ward_no"),
  houseSymbolNo: text("house_symbol_no"),
  familySymbolNo: text("family_symbol_no"),
  dateOfInterview: timestamp("date_of_interview"),

  locality: text("locality"),
  developmentOrganization: text("development_organization"),
  familyHeadName: text("family_head_name"),
  familyHeadPhoneNo: text("family_head_phone_no"),
  totalMembers: integer("total_members"),
  areMembersElsewhere: text("are_members_elsewhere"),
  totalElsewhereMembers: integer("total_elsewhere_members"),
  houseOwnership: text("house_ownership"),
  houseOwnershipOther: text("house_ownership_other"),
  landOwnership: text("land_ownership"),
  landOwnershipOther: text("land_ownership_other"),
  houseBase: text("house_base"),
  houseBaseOther: text("house_base_other"),
  houseOuterWall: text("house_outer_wall"),
  houseOuterWallOther: text("house_outer_wall_other"),
  houseRoof: text("house_roof"),
  houseRoofOther: text("house_roof_other"),
  houseFloor: text("house_floor"),
  houseFloorOther: text("house_floor_other"),
  isHousePassed: text("is_house_passed"),
  isMapArchived: text("is_map_archived"),
  naturalDisasters: text("natural_disasters").array(),
  isSafe: text("is_safe"),
  waterSource: text("water_source"),
  waterPurificationMethods: text("water_purification_methods").array(),
  toiletType: text("toilet_type"),
  solidWasteManagement: text("solid_waste_management"),
  primaryCookingFuel: text("primary_cooking_fuel"),
  primaryEnergySource: text("primary_energy_source"),
  roadStatus: text("road_status"),
  timeToPublicBus: text("time_to_public_bus"),
  timeToMarket: text("time_to_market"),
  distanceToActiveRoad: text("distance_to_active_road"),
  facilities: text("facilities").array(),
  hasPropertiesElsewhere: text("has_properties_elsewhere"),
  hasFemaleNamedProperties: text("has_female_named_properties"),
  organizationsLoanedFrom: text("organizations_loaned_from").array(),
  loanUses: text("loan_uses").array(),
  timeToBank: text("time_to_bank"),
  financialAccounts: text("financial_accounts").array(),
  haveHealthInsurance: text("have_health_insurance"),
  consultingHealthOrganization: text("consulting_health_organization"),
  timeToHealthOrganization: text("time_to_health_organization"),
  incomeSources: text("income_sources").array(),
  municipalSuggestions: text("municipal_suggestions").array(),
  haveAgriculturalLand: text("have_agricultural_land"),
  agriculturalLands: text("agricultural_lands").array(),
  areInvolvedInAgriculture: text("are_involved_in_agriculture"),
  foodCrops: text("food_crops").array(),
  pulses: text("pulses").array(),
  oilSeeds: text("oil_seeds").array(),
  vegetables: text("vegetables").array(),
  fruits: text("fruits").array(),
  spices: text("spices").array(),
  cashCrops: text("cash_crops").array(),
  areInvolvedInHusbandry: text("are_involved_in_husbandry"),
  animals: text("animals").array(),
  animalProducts: text("animal_products").array(),
  haveAquaculture: text("have_aquaculture"),
  pondNumber: integer("pond_number"),
  pondArea: doublePrecision("pond_area"),
  fishProduction: doublePrecision("fish_production"),
  haveApiary: text("have_apiary"),
  hiveNumber: integer("hive_number"),
  honeyProduction: doublePrecision("honey_production"),
  honeySales: doublePrecision("honey_sales"),
  honeyRevenue: doublePrecision("honey_revenue"),
  hasAgriculturalInsurance: text("has_agricultural_insurance"),
  monthsInvolvedInAgriculture: text("months_involved_in_agriculture"),
  agriculturalMachines: text("agricultural_machines").array(),
  haveRemittance: text("have_remittance"),
  remittanceExpenses: text("remittance_expenses").array(),
  deviceId: text("device_id"),
});

export default buddhashantiHousehold;
