const agriData = {
  audio_monitoring: "1737201362376.m4a",
  NBIZ: null,
  enumerator_introduction: {
    enumerator_name: "Sarbagya Shrestha",
    enumerator_id: "Sarbagya Shrestha",
    enumerator_phone: "9823833365",
    building_token_number: "0bywnzaq",
  },
  business_name: "Trilo Krishi Farm",
  b_addr: {
    ward_no: 2,
    area_code: "2001",
    biz_no: 2,
    locality: "Gyalo Tole",
  },
  b: {
    op_name: "Trilochan Bhusal",
    opph: "9823833365",
    op_age: 25,
    op_gender: "male",
    op_edu_lvl: "masters_level",
  },
  business_nature: "agriculture_livestock_fish_and_beekeeping_farm",
  business_nature_other: null,
  business_type: null,
  business_type_other: null,
  is_registered: "yes",
  registered_bodies:
    "household_and_microindustries commerce_office ministry_of_health_department ward_office",
  registered_bodies_other: null,
  statutory_status: "individual",
  statutory_status_other: null,
  has_pan: "yes",
  pan_no: 123456789,
  ownership_status: null,
  ownership_status_oth: null,
  hotel: {
    accomodation_type: null,
    room_no: null,
    bed_no: null,
    room_type: null,
    has_hall: null,
    hcpcty: null,
  },
  bag: {
    agri_business: "agriculatural_products",
    bagd: {
      fcrops: "paddy corn wheat millet barley phapar junelo kaguno other",
      fcrop_details_count: "9",
      pulses:
        "pigeon_pea black_gram lentil chickpea soyabean snake_bean bean horse_gram pea other",
      pulse_details_count: "10",
      oseeds: "mustard flax sunflower other",
      oseed_details_count: "4",
      vtables:
        "potato cauliflower cabbage tomato radish carrot turnip capsicum okra brinjal onion string_bean red_kidney_bean pumpkin cucumber bitter_gourd luffa snake_gourd calabash balsam_apple mushroom squice mustard_greens garden_cress spinach colocasia yam other",
      vtable_details_count: "28",
      fruits:
        "mango jackfruit litchi banana lemon orange nibuwa pomelo sweet_orange jyamir sweet_lemon pineapple papaya avocado guava kiwi plum peach pear pomegranate walnut japanese_persimmon hog_plum",
      fruit_details_count: "23",
      spices:
        "coriander garlic turmeric ginger chili_pepper other fenugreek cumin sichuan_pepper black_pepper cinnamomum_tamala",
      spice_details_count: "11",
      ccrops:
        "cotton cardamom tea betel_nut tobacco other sugar_cane coffee rubber jute",
      ccrop_details_count: "10",
      "fcrop_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/fcrop_details",
      "pulse_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/pulse_details",
      "oseed_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/oseed_details",
      "vtable_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/vtable_details",
      "fruit_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/fruit_details",
      "spice_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/spice_details",
      "ccrop_details@odata.navigationLink":
        "Submissions('uuid%3Aff7060e4-c0df-4975-bac0-be502a03d753')/bag/bagd/ccrop_details",
    },
    b_animals: null,
    banimal_details_count: "0",
    b_aprods: null,
    baprod_details_count: "0",
    aquaculture_details: {
      aquaculture_ward_no: null,
      pond_no: null,
      BC01_3: null,
      BC01_5: null,
      BC01_7: null,
      pond_area: null,
      BC01_9: null,
      fish_prod: null,
    },
    apiculture_details: {
      dapi: null,
      apiculture_ward_no: null,
      hive_no: null,
      honey_prod: null,
    },
  },
  investment: 2000000,
  business_location_ownership: "own_house",
  business_location_ownership_oth: null,
  emp: {
    has_partners: "no",
    prt: {
      total_partners: null,
      nepali_male_partners: null,
      nepali_female_partners: null,
      has_foreign_partners: null,
      foreign_male_partners: null,
      foreign_female_partners: null,
      PTOT: null,
      NIF01: null,
    },
    has_involved_family: "no",
    efam: {
      total_involved_family: null,
      male_involved_family: null,
      female_involved_family: null,
      IFTOT: null,
      NIF01: null,
    },
    has_perm_employees: "no",
    etemp: {
      total_perm_employees: null,
      nepali_male_perm_employees: null,
      nepali_female_perm_employees: null,
      has_foreign_perm_employees: null,
      foreign_male_perm_employees: null,
      foreign_female_perm_employees: null,
      frgnpemp: null,
      PERMTOT: null,
      NIF01: null,
    },
    frgnpemp_cnt: null,
    has_temp_employees: "no",
    eperm: {
      total_temp_employees: null,
      nepali_male_temp_employees: null,
      nepali_female_temp_employees: null,
      has_foreign_temp_employees: null,
      foreign_male_temp_employees: null,
      foreign_female_temp_employees: null,
      frgntemp: null,
      TEMPTOT: null,
      NIF01: null,
    },
    frgntemp_cnt: null,
  },
  b_location: {
    type: "Point",
    coordinates: [85.3840339, 27.6895641, 1286.800048828125],
    properties: {
      accuracy: 20.241,
    },
  },
  bimg: "1737201343317.jpg",
  bimg_selfie: "1737201359833.jpg",
  meta: {
    instanceID: "uuid:ff7060e4-c0df-4975-bac0-be502a03d753",
    instanceName: "Trilo Krishi Farm Trilochan Bhusal",
  },
  __id: "uuid:ff7060e4-c0df-4975-bac0-be502a03d753",
  __system: {
    submissionDate: "2025-01-18T11:58:09.319Z",
    updatedAt: null,
    submitterId: "32",
    submitterName: "Tester",
    attachmentsPresent: 3,
    attachmentsExpected: 3,
    status: null,
    reviewState: null,
    deviceId: "collect:BgMTfEPWdPuOjfpc",
    edits: 0,
    formVersion: "1",
  },
};
const hotelData = {
  audio_monitoring: "1737200582820.m4a",
  NBIZ: null,
  enumerator_introduction: {
    enumerator_name: "Sarbagya Shrestha",
    enumerator_id: "C7SU6BMQ",
    enumerator_phone: "9823833365",
    building_token_number: "09qkygxh ",
  },
  business_name: "Hamro Ramro Hotel ",
  b_addr: {
    ward_no: 2,
    area_code: "2001",
    biz_no: 1,
    locality: "Shambhawana Chowk",
  },
  b: {
    op_name: "Trilochan Ji",
    opph: "9823833365",
    op_age: 30,
    op_gender: "male",
    op_edu_lvl: "masters_level",
  },
  business_nature: "service_sales",
  business_nature_other: null,
  business_type: "hotel_lodge_and_restaurant",
  business_type_other: null,
  is_registered: "yes",
  registered_bodies:
    "household_and_microindustries commerce_office ministry_of_health_department ward_office",
  registered_bodies_other: null,
  statutory_status: "individual",
  statutory_status_other: null,
  has_pan: "yes",
  pan_no: 123456789,
  ownership_status: null,
  ownership_status_oth: null,
  hotel: {
    accomodation_type: "food_only",
    room_no: 20,
    bed_no: 40,
    room_type: "air_conditioner normal_room attached_bathroom_and_toilet",
    has_hall: "yes",
    hcpcty: 200,
  },
  bag: {
    agri_business: null,
    bagd: {
      fcrops: null,
      fcrop_details_count: null,
      pulses: null,
      pulse_details_count: null,
      oseeds: null,
      oseed_details_count: null,
      vtables: null,
      vtable_details_count: null,
      fruits: null,
      fruit_details_count: null,
      spices: null,
      spice_details_count: null,
      ccrops: null,
      ccrop_details_count: null,
    },
    b_animals: null,
    banimal_details_count: null,
    b_aprods: null,
    baprod_details_count: null,
    aquaculture_details: {
      aquaculture_ward_no: null,
      pond_no: null,
      BC01_3: null,
      BC01_5: null,
      BC01_7: null,
      pond_area: null,
      BC01_9: null,
      fish_prod: null,
    },
    apiculture_details: {
      dapi: null,
      apiculture_ward_no: null,
      hive_no: null,
      honey_prod: null,
    },
  },
  investment: 2000000,
  business_location_ownership: "own_house",
  business_location_ownership_oth: null,
  emp: {
    has_partners: "yes",
    prt: {
      total_partners: 2,
      nepali_male_partners: 1,
      nepali_female_partners: 0,
      has_foreign_partners: "yes",
      foreign_male_partners: 1,
      foreign_female_partners: 0,
      PTOT: "2",
      NIF01: null,
    },
    has_involved_family: "yes",
    efam: {
      total_involved_family: 2,
      male_involved_family: 1,
      female_involved_family: 1,
      IFTOT: "2",
      NIF01: null,
    },
    has_perm_employees: "yes",
    etemp: {
      total_perm_employees: 4,
      nepali_male_perm_employees: 1,
      nepali_female_perm_employees: 1,
      has_foreign_perm_employees: "yes",
      foreign_male_perm_employees: 1,
      foreign_female_perm_employees: 1,
      frgnpemp: "2",
      PERMTOT: "4",
      NIF01: null,
    },
    frgnpemp_cnt: "niger",
    has_temp_employees: "yes",
    eperm: {
      total_temp_employees: 4,
      nepali_male_temp_employees: 1,
      nepali_female_temp_employees: 1,
      has_foreign_temp_employees: "yes",
      foreign_male_temp_employees: 1,
      foreign_female_temp_employees: 1,
      frgntemp: "2",
      TEMPTOT: "4",
      NIF01: null,
    },
    frgntemp_cnt: "azerbaijan",
    "partners@odata.navigationLink":
      "Submissions('uuid%3A9e5a3f29-77cb-4372-9687-4b4947554220')/emp/partners",
  },
  b_location: {
    type: "Point",
    coordinates: [85.3836031, 27.6895602, 1291.4000244140625],
    properties: {
      accuracy: 7.9,
    },
  },
  bimg: "1737200543214.jpg",
  bimg_selfie: "1737200580100.jpg",
  meta: {
    instanceID: "uuid:9e5a3f29-77cb-4372-9687-4b4947554220",
    instanceName: "Hamro Ramro Hotel  Trilochan Ji",
  },
  __id: "uuid:9e5a3f29-77cb-4372-9687-4b4947554220",
  __system: {
    submissionDate: "2025-01-18T11:45:07.784Z",
    updatedAt: null,
    submitterId: "32",
    submitterName: "Tester",
    attachmentsPresent: 3,
    attachmentsExpected: 3,
    status: null,
    reviewState: null,
    deviceId: "collect:BgMTfEPWdPuOjfpc",
    edits: 0,
    formVersion: "1",
  },
};
