import { z } from "zod";

export const createIndividualSchema = z.object({
  parentId: z.string().min(1, "Parent ID is required"),
  wardNo: z.number().min(1, "Ward number is required"),
  deviceId: z.string().optional(),
  name: z.string().min(1, "Name is required"),
  gender: z.string().min(1, "Gender is required"),
  age: z.number().optional(),
  familyRole: z.string().optional(),
  citizenOf: z.string().optional(),
  citizenOfOther: z.string().optional(),
  caste: z.string().optional(),
  casteOther: z.string().optional(),
  ancestorLanguage: z.string().optional(),
  ancestorLanguageOther: z.string().optional(),
  primaryMotherTongue: z.string().optional(),
  primaryMotherTongueOther: z.string().optional(),
  religion: z.string().optional(),
  religionOther: z.string().optional(),
  maritalStatus: z.string().optional(),
  marriedAge: z.number().optional(),
  hasChronicDisease: z.string().optional(),
  primaryChronicDisease: z.string().optional(),
  isSanitized: z.string().optional(),
  isDisabled: z.string().optional(),
  disabilityType: z.string().optional(),
  disabilityTypeOther: z.string().optional(),
  disabilityCause: z.string().optional(),
  hasBirthCertificate: z.string().optional(),
  gaveLiveBirth: z.string().optional(),
  aliveSons: z.number().optional(),
  aliveDaughters: z.number().optional(),
  totalBornChildren: z.number().optional(),
  hasDeadChildren: z.string().optional(),
  deadSons: z.number().optional(),
  deadDaughters: z.number().optional(),
  totalDeadChildren: z.number().optional(),
  gaveRecentLiveBirth: z.string().optional(),
  recentBornSons: z.number().optional(),
  recentBornDaughters: z.number().optional(),
  totalRecentChildren: z.number().optional(),
  recentDeliveryLocation: z.string().optional(),
  prenatalCheckups: z.number().optional(),
  firstDeliveryAge: z.number().optional(),
  isPresent: z.string().optional(),
  absenteeAge: z.number().optional(),
  absenteeEducationalLevel: z.string().optional(),
  absenceReason: z.string().optional(),
  absenteeLocation: z.string().optional(),
  absenteeProvince: z.string().optional(),
  absenteeDistrict: z.string().optional(),
  absenteeCountry: z.string().optional(),
  absenteeHasSentCash: z.string().optional(),
  absenteeCashAmount: z.number().optional(),
  literacyStatus: z.string().optional(),
  schoolPresenceStatus: z.string().optional(),
  educationalLevel: z.string().optional(),
  primarySubject: z.string().optional(),
  goesSchool: z.string().optional(),
  schoolBarrier: z.string().optional(),
  hasTraining: z.string().optional(),
  training: z.string().optional(),
  monthsTrained: z.number().optional(),
  primarySkill: z.string().optional(),
  hasInternetAccess: z.string().optional(),
  financialWorkDuration: z.string().optional(),
  primaryOccupation: z.string().optional(),
  workBarrier: z.string().optional(),
  workAvailability: z.string().optional(),
});

export const updateIndividualSchema = z.object({
  id: z.string().min(1, "Individual ID is required"),
  parentId: z.string().min(1, "Parent ID is required").optional(),
  wardNo: z.number().min(1, "Ward number is required").optional(),
  deviceId: z.string().optional(),
  name: z.string().min(1, "Name is required").optional(),
  gender: z.string().min(1, "Gender is required").optional(),
  age: z.number().optional(),
  familyRole: z.string().optional(),
  citizenOf: z.string().optional(),
  citizenOfOther: z.string().optional(),
  caste: z.string().optional(),
  casteOther: z.string().optional(),
  ancestorLanguage: z.string().optional(),
  ancestorLanguageOther: z.string().optional(),
  primaryMotherTongue: z.string().optional(),
  primaryMotherTongueOther: z.string().optional(),
  religion: z.string().optional(),
  religionOther: z.string().optional(),
  maritalStatus: z.string().optional(),
  marriedAge: z.number().optional(),
  hasChronicDisease: z.string().optional(),
  primaryChronicDisease: z.string().optional(),
  isSanitized: z.string().optional(),
  isDisabled: z.string().optional(),
  disabilityType: z.string().optional(),
  disabilityTypeOther: z.string().optional(),
  disabilityCause: z.string().optional(),
  hasBirthCertificate: z.string().optional(),
  gaveLiveBirth: z.string().optional(),
  aliveSons: z.number().optional(),
  aliveDaughters: z.number().optional(),
  totalBornChildren: z.number().optional(),
  hasDeadChildren: z.string().optional(),
  deadSons: z.number().optional(),
  deadDaughters: z.number().optional(),
  totalDeadChildren: z.number().optional(),
  gaveRecentLiveBirth: z.string().optional(),
  recentBornSons: z.number().optional(),
  recentBornDaughters: z.number().optional(),
  totalRecentChildren: z.number().optional(),
  recentDeliveryLocation: z.string().optional(),
  prenatalCheckups: z.number().optional(),
  firstDeliveryAge: z.number().optional(),
  isPresent: z.string().optional(),
  absenteeAge: z.number().optional(),
  absenteeEducationalLevel: z.string().optional(),
  absenceReason: z.string().optional(),
  absenteeLocation: z.string().optional(),
  absenteeProvince: z.string().optional(),
  absenteeDistrict: z.string().optional(),
  absenteeCountry: z.string().optional(),
  absenteeHasSentCash: z.string().optional(),
  absenteeCashAmount: z.number().optional(),
  literacyStatus: z.string().optional(),
  schoolPresenceStatus: z.string().optional(),
  educationalLevel: z.string().optional(),
  primarySubject: z.string().optional(),
  goesSchool: z.string().optional(),
  schoolBarrier: z.string().optional(),
  hasTraining: z.string().optional(),
  training: z.string().optional(),
  monthsTrained: z.number().optional(),
  primarySkill: z.string().optional(),
  hasInternetAccess: z.string().optional(),
  financialWorkDuration: z.string().optional(),
  primaryOccupation: z.string().optional(),
  workBarrier: z.string().optional(),
  workAvailability: z.string().optional(),
});

export type CreateIndividualInput = z.infer<typeof createIndividualSchema>;
export type UpdateIndividualInput = z.infer<typeof updateIndividualSchema>;
