import {
  Type,
  Image,
  Table,
  Quote,
  List,
  Video,
  Heading,
  FileText,
  Layout,
  Bell,
  ListTree,
  GalleryHorizontal as ButtonIcon,
  FormInput,
  TrendingUp as Chart,
  MessageSquare,
  Code,
  FileJson,
  Map,
  Music,
  Youtube,
  Grid,
  Columns,
  BoxSelect,
  StickyNote,
  Info,
} from "lucide-react";

export const NodeTypeColors = {
  heading: {
    bg: "bg-indigo-100",
    bgLight: "bg-indigo-50",
    text: "text-indigo-700",
    border: "border-indigo-200",
    icon: <Heading className="w-5 h-5 text-indigo-600" />,
  },
  paragraph: {
    bg: "bg-blue-100",
    bgLight: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    icon: <Type className="w-5 h-5 text-blue-600" />,
  },
  list: {
    bg: "bg-green-100",
    bgLight: "bg-green-50",
    text: "text-green-700",
    border: "border-green-200",
    icon: <List className="w-5 h-5 text-green-600" />,
  },
  quote: {
    bg: "bg-amber-100",
    bgLight: "bg-amber-50",
    text: "text-amber-700",
    border: "border-amber-200",
    icon: <Quote className="w-5 h-5 text-amber-600" />,
  },
  image: {
    bg: "bg-fuchsia-100",
    bgLight: "bg-fuchsia-50",
    text: "text-fuchsia-700",
    border: "border-fuchsia-200",
    icon: <Image className="w-5 h-5 text-fuchsia-600" />,
  },
  video: {
    bg: "bg-rose-100",
    bgLight: "bg-rose-50",
    text: "text-rose-700",
    border: "border-rose-200",
    icon: <Video className="w-5 h-5 text-rose-600" />,
  },
  table: {
    bg: "bg-purple-100",
    bgLight: "bg-purple-50",
    text: "text-purple-700",
    border: "border-purple-200",
    icon: <Table className="w-5 h-5 text-purple-600" />,
  },
  chart: {
    bg: "bg-cyan-100",
    bgLight: "bg-cyan-50",
    text: "text-cyan-700",
    border: "border-cyan-200",
    icon: <Chart className="w-5 h-5 text-cyan-600" />,
  },
  section: {
    bg: "bg-orange-100",
    bgLight: "bg-orange-50",
    text: "text-orange-700",
    border: "border-orange-200",
    icon: <Layout className="w-5 h-5 text-orange-600" />,
  },
  callout: {
    bg: "bg-yellow-100",
    bgLight: "bg-yellow-50",
    text: "text-yellow-700",
    border: "border-yellow-200",
    icon: <Bell className="w-5 h-5 text-yellow-600" />,
  },
  toc: {
    bg: "bg-slate-100",
    bgLight: "bg-slate-50",
    text: "text-slate-700",
    border: "border-slate-200",
    icon: <ListTree className="w-5 h-5 text-slate-600" />,
  },
  button: {
    bg: "bg-emerald-100",
    bgLight: "bg-emerald-50",
    text: "text-emerald-700",
    border: "border-emerald-200",
    icon: <ButtonIcon className="w-5 h-5 text-emerald-600" />,
  },
  form: {
    bg: "bg-teal-100",
    bgLight: "bg-teal-50",
    text: "text-teal-700",
    border: "border-teal-200",
    icon: <FormInput className="w-5 h-5 text-teal-600" />,
  },
  comment: {
    bg: "bg-pink-100",
    bgLight: "bg-pink-50",
    text: "text-pink-700",
    border: "border-pink-200",
    icon: <MessageSquare className="w-5 h-5 text-pink-600" />,
  },
  code: {
    bg: "bg-zinc-100",
    bgLight: "bg-zinc-50",
    text: "text-zinc-700",
    border: "border-zinc-200",
    icon: <Code className="w-5 h-5 text-zinc-600" />,
  },
  json: {
    bg: "bg-neutral-100",
    bgLight: "bg-neutral-50",
    text: "text-neutral-700",
    border: "border-neutral-200",
    icon: <FileJson className="w-5 h-5 text-neutral-600" />,
  },
  map: {
    bg: "bg-lime-100",
    bgLight: "bg-lime-50",
    text: "text-lime-700",
    border: "border-lime-200",
    icon: <Map className="w-5 h-5 text-lime-600" />,
  },
  audio: {
    bg: "bg-sky-100",
    bgLight: "bg-sky-50",
    text: "text-sky-700",
    border: "border-sky-200",
    icon: <Music className="w-5 h-5 text-sky-600" />,
  },
  embed: {
    bg: "bg-red-100",
    bgLight: "bg-red-50",
    text: "text-red-700",
    border: "border-red-200",
    icon: <Youtube className="w-5 h-5 text-red-600" />,
  },
  grid: {
    bg: "bg-violet-100",
    bgLight: "bg-violet-50",
    text: "text-violet-700",
    border: "border-violet-200",
    icon: <Grid className="w-5 h-5 text-violet-600" />,
  },
  columns: {
    bg: "bg-gray-100",
    bgLight: "bg-gray-50",
    text: "text-gray-700",
    border: "border-gray-200",
    icon: <Columns className="w-5 h-5 text-gray-600" />,
  },
  container: {
    bg: "bg-stone-100",
    bgLight: "bg-stone-50",
    text: "text-stone-700",
    border: "border-stone-200",
    icon: <BoxSelect className="w-5 h-5 text-stone-600" />,
  },
  note: {
    bg: "bg-blue-100",
    bgLight: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    icon: <StickyNote className="w-5 h-5 text-blue-600" />,
  },
  info: {
    bg: "bg-sky-100",
    bgLight: "bg-sky-50",
    text: "text-sky-700",
    border: "border-sky-200",
    icon: <Info className="w-5 h-5 text-sky-600" />,
  },
} as const;

export type NodeType = keyof typeof NodeTypeColors;
